name: "Linting"
on: 
  pull_request:
  push:
    branches:
      - master

jobs:
    awesome-lint:
      strategy:
        fail-fast: false
        matrix:
          files:
            - "readme.md"
      runs-on: ubuntu-latest
      steps:
        - name: "Checkout repo"
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: "Install Node"
          uses: actions/setup-node@v4
          with:
            node-version: 'latest'
        - name: "Lint ${{ matrix.files }}"
          run: npx -y awesome-lint ${{ matrix.files }}
    awesome-bot:
      strategy:
        fail-fast: false
        matrix:
          files:
            - "readme.md"
      runs-on: ubuntu-latest
      steps:
        - name: "Checkout repo"
          uses: actions/checkout@v2.0.0
          with:
            fetch-depth: 0
        - name: "Install Ruby"
          uses: ruby/setup-ruby@v1
          with:
            ruby-version: 3.0.1
            bundler-cache: true
        - name: "Install awesome-bot"
          run: gem install awesome_bot
        - name: "Lint ${{ matrix.files }}"
          run: awesome_bot --allow-redirect ${{ matrix.files }} --white-list crates.io
